---
- name: Exploring the template module and jinja expressions
  hosts: planetexpress
  gather_facts: no   # runs the "setup" module on remote hosts

  # these variables are used to build templates
  vars_files:
    - misson.json


  tasks:
    - name: challenge03
      template: 
        src: templates/mission-orders.txt.j2  
        dest: "~/{{item.mission}}-mission-orders.txt"
      vars:
        planet: "{{item.planet"}}"        
      loop: "{{items}}"
