---
- name: Wednesday Morning Challenge
  hosts: planetexpress
  gather_facts: yes # runs by default

  vars_files:
    - ~/ans/myvars.yml

  tasks:

    - name: Install cowsay on CentOS machines
      yum:
        name: cowsay
        state: present
      become: yes # run as sudo
      when: ansible_distribution == "CentOS"

    - name: Install cowsay on Ubuntu machines
      apt:
        name: cowsay
        state: present
      become: yes # run as sudo
      when: ansible_distribution == "Ubuntu"

    - name: loop through the commands
      shell: "{{item}}"
      loop: "{{commands}}"
